
CREATE USER 'KPVK'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';
GRANT USAGE ON *.* TO 'KPVK'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `KPVK`;
GRANT ALL PRIVILEGES ON `KPVK`.* TO 'KPVK'@'localhost';



CREATE USER 'KPVK_test'@'localhost' IDENTIFIED VIA mysql_native_password USING '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9';
GRANT USAGE ON *.* TO 'KPVK_test'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `KPVK_test`;
GRANT ALL PRIVILEGES ON `KPVK_test`.* TO 'KPVK_test'@'localhost';

SELECT PASSWORD('123456'); #'*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9'

SELECT 1 + 1 AS ans



use KPVK_test;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
	user_password VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(255) NOT NULL,
    gender SET('male','female','other'),
    address VARCHAR(255) NOT NULL,
    village VARCHAR(255) NOT NULL,
	user_status BOOLEAN,
    doj DATETIME,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=INNODB;

drop table kpvk_test.user;

INSERT INTO user(user_name,user_password,mobile_number,gender,address,village,user_status,doj)
VALUES('mustaq','*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9','9966244689','male','marrama temple street ','Kalyandurgam',true,now());
